### ISSUE TITLE
Chapter2

### ISSUE THREAD

**Issue by TriOakTrunk** [TriOakTrunk/Nextjs-learn#3]
# 対象
[Chapter2: CSS Styling](https://nextjs.org/learn/dashboard-app/css-styling)
> [!WARNING]
> この章の内容はNext特有のものではない。
## 📖 内容

Next.js でのスタイリング方法について学ぶ章。

---

### 1️⃣ グローバルスタイルの適用
- `global.css` を `app/ui/` に配置し、全体のスタイルを定義
- ルートレイアウト `app/layout.tsx` で `import './ui/global.css'` し、アプリ全体に適用
- `:root` を使って CSS 変数を定義可能

---

### 2️⃣ Tailwind CSS の利用
- `pnpm create next-app` でプロジェクト作成時に Tailwind CSS を選択すると、自動でセットアップされる
- `tailwind.config.js` でカスタマイズ可能
- クラス名を直接 JSX 内で適用できる 
  ```tsx
  <h1 className="text-blue-500">Hello, Tailwind!</h1>
  ```
- ユーティリティクラスを組み合わせることで効率的なデザインが可能

---

### 3️⃣ CSS Modules の使用
- `.module.css` 拡張子を使用し、コンポーネントごとにスコープされたスタイルを定義
- クラス名の競合を防ぐことができる
- 例：  
  ```css
  /* button.module.css */
  .btn {
    background-color: blue;
    color: white;
    padding: 10px;
  }
  ```
  ```tsx
  import styles from './button.module.css';

  export default function Button() {
    return <button className={styles.btn}>Click Me</button>;
  }
  ```

---

この章では、Next.js のアプリケーションに適した **グローバルCSS / Tailwind CSS / CSS Modules** の使用方法を学ぶ。
